[package]
name = "euler3"
version = "0.1.0"
authors = ["Keith Miller <keithmss@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num   = "0.4.0"
rayon = "1.5.1"
